# Generated by Django 4.1.7 on 2023-03-29 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreManagerApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='CreatedOn',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='orders',
            name='CreatedOn',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='CreatedOn',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='store',
            name='CreatedOn',
            field=models.DateTimeField(),
        ),
    ]
