# Generated by Django 4.1.7 on 2023-04-02 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreManagerApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='StoreImage',
            field=models.ImageField(default=1, upload_to='Stores/'),
            preserve_default=False,
        ),
    ]
