# Generated by Django 4.1.7 on 2023-04-02 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreManagerApp', '0002_store_storeimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='CategoryImage',
            field=models.ImageField(default=1, upload_to='Categories/'),
            preserve_default=False,
        ),
    ]
