# Generated by Django 4.1.7 on 2023-04-03 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StoreManagerApp', '0003_category_categoryimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='Products',
        ),
        migrations.RemoveField(
            model_name='store',
            name='Categories',
        ),
        migrations.AddField(
            model_name='product',
            name='Category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='StoreManagerApp.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='Store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='StoreManagerApp.store'),
        ),
    ]
