# Generated by Django 4.1.7 on 2023-04-03 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StoreManagerApp', '0004_remove_category_products_remove_store_categories_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='CategoryImage',
            new_name='Image',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='CategoryName',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='ProductDecription',
            new_name='Decription',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='ProductImage',
            new_name='Image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='ProductName',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='ProductPrice',
            new_name='Price',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='StoreImage',
            new_name='Image',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='StoreName',
            new_name='Name',
        ),
    ]
