# Generated by Django 4.1.7 on 2023-03-30 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreManagerApp', '0005_alter_category_createdby_alter_category_createdon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ProductImage',
            field=models.ImageField(default=1, upload_to='Images/'),
            preserve_default=False,
        ),
    ]
