# Generated by Django 4.1.7 on 2023-04-05 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StoreManagerApp', '0005_rename_categoryimage_category_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='OrderedProducts',
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField(default=1)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StoreManagerApp.product')),
            ],
        ),
        migrations.AddField(
            model_name='orders',
            name='OrderItems',
            field=models.ManyToManyField(to='StoreManagerApp.orderitem'),
        ),
    ]
