# Generated by Django 4.1.7 on 2023-05-16 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreManagerApp', '0007_orders_location_orders_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='Location',
            field=models.TextField(max_length=255),
        ),
    ]
