# Generated by Django 4.1.7 on 2023-05-17 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreManagerApp', '0008_alter_orders_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='IsAdvertiser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='IsSimpleUser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='IsStoreManager',
            field=models.BooleanField(default=False),
        ),
    ]
