# Generated by Django 4.1.7 on 2023-05-19 21:17

import StoreManagerApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreManagerApp', '0010_customuser_isadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='OrderID',
            field=models.CharField(default=StoreManagerApp.models.generate_order_id, editable=False, max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='Status',
            field=models.CharField(choices=[('Preparing', 'Preparing'), ('OnDelivery', 'OnDelivery'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled')], default='Preparing', max_length=10),
        ),
    ]
