# Generated by Django 4.1.7 on 2023-05-19 21:37

import StoreManagerApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreManagerApp', '0011_orders_orderid_alter_orders_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='CategoryID',
            field=models.CharField(default=StoreManagerApp.models.generate_Category_id, editable=False, max_length=6, unique=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='OrderItemID',
            field=models.CharField(default=StoreManagerApp.models.generate_OrderItem_id, editable=False, max_length=6, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ProductID',
            field=models.CharField(default=StoreManagerApp.models.generate_product_id, editable=False, max_length=6, unique=True),
        ),
        migrations.AddField(
            model_name='store',
            name='StoreID',
            field=models.CharField(default=StoreManagerApp.models.generate_store_id, editable=False, max_length=6, unique=True),
        ),
    ]
