# Generated by Django 4.1.7 on 2023-05-20 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StoreManagerApp', '0012_category_categoryid_orderitem_orderitemid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Decription',
            new_name='Description',
        ),
    ]
